name: Gitea Actions Demo
run-name: ${{ gitea.actor }} is testing out Gitea Actions 🚀
on: [push]
jobs:
  Explore-Gitea-Actions:
    runs-on: alpine
    container:
      volumes:
        - /var/lib/act_runner/.ssh:/root/.ssh
    steps:
      - run: ls /root/.ssh
      - run: whoami
      - run: echo $HOME
      - run: ssh git@10.0.0.183 cd '/var/www/html && git pull'
      - run: ls ~/.ssh

