name: Gitea Actions Demo
run-name: Telling server to pull changes.
on: [push]
jobs:
  Explore-Gitea-Actions:
    runs-on: alpine
    container:
      volumes:
        - /var/lib/act_runner/.ssh:/root/.ssh
    steps:
       - run: echo "hi"
#      - run: ssh git@10.0.0.183 cd '/var/www/html && git pull'

